// swift-tools-version: 5.9
import PackageDescription

// Auto-generated by CI. Do not edit manually.
let package = Package(
    name: "BaklavaSDK",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "BaklavaSDK", targets: ["BaklavaSDK"])
    ],
    targets: [
        .binaryTarget(
            name: "BaklavaSDK",
            url: "https://github.com/TerraceApps/baklava-ios-sdk/releases/download/v1.0.0/BaklavaSDK.xcframework.zip",
            checksum: "75264257eca7fe39825668030b9808b09ad12c58a34c3eb68d7cf666ea304ddb"
        )
    ]
)
