// swift-tools-version: 5.9
import PackageDescription

// Auto-generated by CI. Do not edit manually.
let package = Package(
    name: "BaklavaSDK",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "BaklavaSDK", targets: ["BaklavaSDK"])
    ],
    targets: [
        .binaryTarget(
            name: "BaklavaSDK",
            url: "https://github.com/TerraceApps/baklava-ios-sdk/releases/download/v1.0.0/BaklavaSDK.xcframework.zip",
            checksum: "59715d088d59829ad98890172154e00fa77838eda79ff5e01ccbc722808d6580"
        )
    ]
)
