// swift-tools-version: 5.9
import PackageDescription

// Auto-generated by CI. Do not edit manually.
let package = Package(
    name: "BaklavaSDK",
    platforms: [.iOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "BaklavaSDK", targets: ["BaklavaSDK"])
    ],
    targets: [
        .binaryTarget(
            name: "BaklavaSDK",
            url: "https://github.com/TerraceApps/baklava-ios-sdk/releases/download/v1.0.0/BaklavaSDK.xcframework.zip",
            checksum: "368023e6b026e820ab7727c9d8172a954dc1d439a4478c420c81abb0d6d41f6d"
        )
    ]
)
